### ISSUE TITLE
In the shell run_fedavg_scaffold_fedpvr.sh , What does the number of devices (N) refer to? Does it mean the number of GPUs or the number of clients?

### ISSUE THREAD

**Issue by GongShuai8210** [lyn1874/fedpvr#1]
What does the number of devices (N) refer to? Does it mean the number of GPUs or the number of clients?

**Comment by lyn1874** [comment]
Hi, thanks for your interest in the code. 

No, the number of devices is simply the number of workers. The number of GPUs depends on your system. For example, if you have one GPU and you want to set up 6 workers, then you basically run the training of these 6 workers on one GPU device. 

I hope this helps.
